name: 'Repository Summarizer'
description:
  'Summarizes the contents of the repository and creates/updates an issue with
  the summary.'
author: 'Your name or organization here'

outputs:
  summary:
    description: 'The summary of the repository contents'

runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
