name: 'Repository Summarizer'
description:
  'Summarizes the contents of the repository and creates/updates an issue with
  the summary.'
author: 'Your name or organization here'

inputs:
  demo_mode:
    description: 'Run in demo mode with hardcoded values'
    required: false
    default: 'false'

outputs:
  summary:
    description: 'The summary of the repository contents'

runs:
  using: docker
  image: Dockerfile
