name: Summarize Action

# This workflow will only run when manually triggered
on:
  workflow_dispatch:

jobs:
  summarize-repo:
    name: Summarize Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run Summarizer
        id: run-summarizer
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Print Output
        id: output
        run: 'echo "Summary: ${steps.test-action.outputs.time}"'
